### ISSUE TITLE
Grace's branch missing

### ISSUE THREAD

**Issue by jkwon825** [stat545ubc-2023/collaborative-group5#12]
HI guys, I'm just reviewing everyone's branches, and I don't see a branch with Grace's name on it. @kuograce713 could you confirm if you have created a branch and merged it with the main branch? thanks!
@nmhowes @LukeLuDongLai

**Comment by nmhowes** [comment]
Yep I saw Grace's and just added her name to make it easier!

**Comment by jkwon825** [comment]
Perfect thanks nicole!
